on: push
name: deploy
jobs: 
    deploy:
        name:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@master
        - name: build and push to docker
          uses: docker/build-push-action@v4
          with:
            name: perepo/repository
            push: true
            tags: ${{ github.sha }}
            repository: perepo/repository
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
  

