on: push
name: deploy
jobs: 
    deploy:
        name:
        runs-on: ubuntu-latest
        steps:

        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}            
        
        - uses: actions/checkout@master

        - name: build and push to docker
          uses: docker/build-push-action@v4
          with:
            context: .
            name: perepo/datagarden
            push: true
            tags: ${{ github.sha }}
            repository: perepo/datagarden
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
  

