on: push
name: deploy
jobs: 
    deploy:
        name:
        runs-on: ubuntu-latest
        permissions:
            packages: write
            contents: read
            attestations: write
            id-token: write
        
        steps:

        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}            
        
        - uses: actions/checkout@master

        - name: build the docker image
          run: docker build . -t perepo/datagarden:${{ github.sha }} -t perepo/datagarden:latest 

        - name: Push to Registry
          run: |
              docker push perepo/datagarden:${{ github.sha }}
              docker push perepo/datagarden:latest   
        
        - name: Logout
          run: docker logout

